import React, { useEffect, useState } from "react";
import { useNavigate, useParams } from "react-router-dom";
import { api } from "../api/client";
import { Card, EmptyState, ErrorNote } from "../components/ui";

export default function ReportsPage() {
  const { projectId } = useParams();
  const navigate = useNavigate();
  const [reports, setReports] = useState(null);
  const [error, setError] = useState("");

  useEffect(() => {
    api.get(`/projects/${projectId}/reports`).then(setReports).catch((e) => setError(e.message));
  }, [projectId]);

  return (
    <div className="mx-auto max-w-3xl px-8 py-10">
      <h2 className="font-serif text-2xl text-ink">Reports</h2>
      <p className="mt-1 text-sm text-ink/60">Generated by completed research runs.</p>

      <div className="mt-6">
        <ErrorNote message={error} />
      </div>

      <div className="mt-4 space-y-2">
        {reports === null && <p className="text-sm text-ink/50">Loading…</p>}
        {reports?.length === 0 && (
          <EmptyState title="No reports yet" description="Run a research task to generate your first report." />
        )}
        {reports?.map((r) => (
          <Card
            key={r._id}
            className="cursor-pointer px-5 py-4 hover:border-pine"
            onClick={() => navigate(`/projects/${projectId}/reports/${r._id}`)}
          >
            <h3 className="font-serif text-lg text-ink">{r.topic}</h3>
            <p className="mt-1 text-xs text-ink/40">{new Date(r.createdAt).toLocaleString()}</p>
          </Card>
        ))}
      </div>
    </div>
  );
}
